version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    labels:
      - dependencies
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /webapp
    labels:
      - dependencies
    schedule:
      interval: daily
    versioning-strategy: increase

  - package-ecosystem: uv
    directory: /
    labels:
      - dependencies
    schedule:
      interval: daily
    versioning-strategy: increase
