changelog:
  categories:
    - title: "✨ Improvements"
      labels:
        - enhancement
    - title: "🐛 Bug Fixes"
      labels:
        - bug
    - title: "📦 Dependencies"
      labels:
        - dependencies
    - title: "🔧 Miscellaneous"
      labels:
        - "*"
  exclude:
    labels:
      - "no-changelog"
