[project]
name = "frekvens"
description = "Toolbox for the Frekvens ESP32 project."
version = "1.0.0"
license = { file = "../LICENSE" }
readme = "../README.md"

[project.urls]
"Homepage" = "https://github.com/VIPnytt/Frekvens"
"Wiki" = "https://github.com/VIPnytt/Frekvens/wiki"
"Bug Reports" = "https://github.com/VIPnytt/Frekvens/issues"

[tool.setuptools.packages.find]
where = ["src"]
