name: Dependabot Updates PlatformIO

on:
  schedule:
    - cron: 9 5 * * 1-5

  workflow_dispatch:

permissions:
  contents: read

jobs:
  context:
    name: Context
    runs-on: ubuntu-slim

    outputs:
      milestone: ${{ steps.check.outputs.milestone }}
      open-pull-requests-limit: ${{ steps.check.outputs.open-pull-requests-limit }}

    steps:
      - name: GitHub Script checks
        id: check
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        with:
          script: |
            const { data: branch } = await github.rest.repos.getBranch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              branch: '${{ github.ref_name }}',
            });
            if (new Date() - new Date(branch.commit.commit.committer.date) > 90 * 86400000) {
              core.info('Branch inactive');
              core.debug('Milestone: none');
              core.setOutput('milestone', '');
              core.debug('Open pull request limit: 0');
              core.setOutput('open-pull-requests-limit', 0);
              return;
            }
            if (process.env['open-pull-requests-limit'] === undefined) {
              core.debug('No open pull request limit configured');
            }
            const limit = Number(process.env['open-pull-requests-limit'] ?? 5);
            core.info(`Open pull request limit: ${limit}`);
            core.setOutput('open-pull-requests-limit', limit);
            if (limit < 1) {
              return;
            }
            if (!process.env.milestone) {
              core.debug('No milestone configured');
              core.setOutput('milestone', '');
              return;
            }
            try {
              const { data: milestone } = await github.rest.issues.getMilestone({
                owner: context.repo.owner,
                repo: context.repo.repo,
                milestone_number: Number(process.env.milestone),
              });
              if (milestone.state === 'open') {
                core.info(`Milestone ${milestone.number}: ${milestone.state}`);
                core.setOutput('milestone', milestone.number);
              } else {
                core.warning(`Milestone ${milestone.number}: ${milestone.state}`);
                core.setOutput('milestone', '');
              }
            } catch (e) {
              if (e.status === 404) {
                core.error(`Milestone ${process.env.milestone} not found`);
                core.setOutput('milestone', '');
              } else {
                throw e;
              }
            }

  github-check:
    name: GitHub check
    needs: context
    runs-on: ubuntu-slim
    if: ${{ needs.context.outputs.open-pull-requests-limit > 0 }}

    outputs:
      dependency-fragments: ${{ steps.pending.outputs.fragments }}

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up uv
        uses: astral-sh/setup-uv@cec208311dfd045dd5311c1add060b2062131d57 # v8.0.0
        with:
          version-file: pyproject.toml
          python-version: 3.14
          activate-environment: true

      - name: Set up Python packages
        run: uv sync --only-group dependabot

      - name: Frekvens GitHub dependabot
        id: pending
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_WORKSPACE: ${{ github.workspace }}
        run: echo "fragments=$(python -m GitHub)" >> "$GITHUB_OUTPUT"
        working-directory: .github/scripts/dependabot/github

  github-update:
    name: GitHub update
    needs:
      - context
      - github-check
    runs-on: ubuntu-slim
    if: ${{ fromJSON(needs.github-check.outputs.dependency-fragments)[0] != null }}

    permissions:
      contents: write
      pull-requests: write

    strategy:
      max-parallel: 1
      matrix:
        fragments: ${{ fromJSON(needs.github-check.outputs.dependency-fragments) }}

    steps:
      - name: GitHub Script pull request check
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        id: check
        with:
          script: |
            const { data: prs } = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'all',
              head: `${context.repo.owner}:dependabot/platformio/${{ matrix.fragments.owner }}/${{ matrix.fragments.repo }}-${{ matrix.fragments.version_new }}`,
              base: '${{ github.ref_name }}',
            });
            let create = prs.length === 0;
            if (create) {
              let count = 0;
              let match = false;
              for (const pr of await github.paginate(
                github.rest.pulls.list,
                {
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  state: 'open',
                  base: '${{ github.ref_name }}',
                  per_page: 100,
                }
              )) {
                if (
                  pr.user.type === 'Bot' &&
                  pr.head.ref.startsWith('dependabot/platformio/')
                ) {
                  if (pr.head.ref.startsWith('dependabot/platformio/${{ matrix.fragments.owner }}/${{ matrix.fragments.repo }}-')) {
                    match = true;
                    break;
                  }
                  count++;
                }
              }
              if (
                !match &&
                count >= ${{ needs.context.outputs.open-pull-requests-limit }}
              ) {
                core.debug('Open pull request limit exceeded');
                create = false;
              }
            }
            core.info(`Create pull request: ${create}`);
            core.setOutput('create', create);

      - name: Checkout
        if: ${{ fromJSON(steps.check.outputs.create) }}
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Update platformio.ini
        if: ${{ fromJSON(steps.check.outputs.create) }}
        run: sed -i "s|${{ matrix.fragments.string_old }}|${{ matrix.fragments.string_new }}|g" platformio.ini

      - name: Create Pull Request
        if: ${{ fromJSON(steps.check.outputs.create) }}
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        id: pr
        with:
          author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          body: |
            Bumps [${{ matrix.fragments.owner }}/${{ matrix.fragments.repo }}](https://github.com/${{ matrix.fragments.owner }}/${{ matrix.fragments.repo }}) from ${{ matrix.fragments.version_old }} to ${{ matrix.fragments.version_new }}.
            - [Releases](https://github.com/${{ matrix.fragments.owner }}/${{ matrix.fragments.repo }}/releases)
            - [Tags](https://github.com/${{ matrix.fragments.owner }}/${{ matrix.fragments.repo }}/tags)
            - [Commits](https://github.com/${{ matrix.fragments.owner }}/${{ matrix.fragments.repo }}/commits)
            - [Compare changes](https://github.com/${{ matrix.fragments.owner }}/${{ matrix.fragments.repo }}/compare/${{ matrix.fragments.commit_old || matrix.fragments.tag_old }}...${{ matrix.fragments.commit_new || matrix.fragments.tag_new }})
          branch: dependabot/platformio/${{ matrix.fragments.owner }}/${{ matrix.fragments.repo }}-${{ matrix.fragments.version_new }}
          commit-message: Bump ${{ matrix.fragments.owner }}/${{ matrix.fragments.repo }} from ${{ matrix.fragments.version_old }} to ${{ matrix.fragments.version_new }} in /
          labels: |
            dependencies
            firmware
          milestone: ${{ needs.context.outputs.milestone }}
          title: Bump ${{ matrix.fragments.owner }}/${{ matrix.fragments.repo }} from ${{ matrix.fragments.version_old }} to ${{ matrix.fragments.version_new }}

      - name: GitHub Script close superseded
        if: ${{ fromJSON(steps.check.outputs.create) }}
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        with:
          script: |
            for (const pr of await github.paginate(
              github.rest.pulls.list,
              {
                owner: context.repo.owner,
                repo: context.repo.repo,
                state: 'open',
                base: '${{ github.ref_name }}',
                per_page: 100,
              }
            )) {
              if (
                pr.number !== Number(${{ steps.pr.outputs.pull-request-number }}) &&
                pr.user.type === 'Bot' &&
                pr.head.ref.startsWith('dependabot/platformio/${{ matrix.fragments.owner }}/${{ matrix.fragments.repo }}-')
              ) {
                await github.rest.issues.createComment({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: pr.number,
                  body: 'Superseded by #${{ steps.pr.outputs.pull-request-number }}.',
                });
                await github.rest.issues.update({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: pr.number,
                  milestone: null,
                });
                await github.rest.pulls.update({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  pull_number: pr.number,
                  state: 'closed',
                });
                core.info(`Closed PR #${pr.number}`);
              }
            }

  platformio-check:
    name: PlatformIO check
    needs: context
    runs-on: ubuntu-slim
    if: ${{ needs.context.outputs.open-pull-requests-limit > 0 }}

    outputs:
      dependency-fragments: ${{ steps.pending.outputs.fragments }}

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up uv
        uses: astral-sh/setup-uv@cec208311dfd045dd5311c1add060b2062131d57 # v8.0.0
        with:
          version-file: pyproject.toml
          python-version: 3.14
          activate-environment: true

      - name: Set up Python packages
        run: uv sync --only-group dependabot --only-group platformio

      - name: Frekvens PlatformIO dependabot
        id: pending
        env:
          GITHUB_WORKSPACE: ${{ github.workspace }}
        run: echo "fragments=$(python -m PlatformIo)" >> "$GITHUB_OUTPUT"
        working-directory: .github/scripts/dependabot/platformio

  platformio-update:
    name: PlatformIO update
    needs:
      - context
      - platformio-check
    runs-on: ubuntu-slim
    if: ${{ fromJSON(needs.platformio-check.outputs.dependency-fragments)[0] != null }}

    permissions:
      contents: write
      pull-requests: write

    strategy:
      max-parallel: 1
      matrix:
        fragments: ${{ fromJSON(needs.platformio-check.outputs.dependency-fragments) }}

    steps:
      - name: GitHub Script pull request check
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        id: check
        with:
          script: |
            const { data: prs } = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'all',
              head: `${context.repo.owner}:dependabot/platformio/${{ matrix.fragments.owner }}/${{ matrix.fragments.name }}-${{ matrix.fragments.version_new }}`,
              base: '${{ github.ref_name }}',
            });
            let create = prs.length === 0;
            if (create) {
              let count = 0;
              let match = false;
              for (const pr of await github.paginate(
                github.rest.pulls.list,
                {
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  state: 'open',
                  base: '${{ github.ref_name }}',
                  per_page: 100,
                }
              )) {
                if (
                  pr.user.type === 'Bot' &&
                  pr.head.ref.startsWith('dependabot/platformio/')
                ) {
                  if (pr.head.ref.startsWith('dependabot/platformio/${{ matrix.fragments.owner }}/${{ matrix.fragments.name }}-')) {
                    match = true;
                    break;
                  }
                  count++;
                }
              }
              if (
                !match &&
                count >= ${{ needs.context.outputs.open-pull-requests-limit }}
              ) {
                core.debug('Open pull request limit exceeded');
                create = false;
              }
            }
            core.info(`Create pull request: ${create}`);
            core.setOutput('create', create);

      - name: Checkout
        if: ${{ fromJSON(steps.check.outputs.create) }}
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Update platformio.ini
        if: ${{ fromJSON(steps.check.outputs.create) }}
        run: sed -i "s|${{ matrix.fragments.string_old }}|${{ matrix.fragments.string_new }}|g" platformio.ini

      - name: Create Pull Request
        if: ${{ fromJSON(steps.check.outputs.create) }}
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        id: pr
        with:
          author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          body: |
            Bumps [${{ matrix.fragments.owner }}/${{ matrix.fragments.name }}](https://registry.platformio.org/${{ matrix.fragments.type }}/${{ matrix.fragments.owner }}/${{ matrix.fragments.name }}?version=${{ matrix.fragments.version_new }}) from ${{ matrix.fragments.version_old }} to ${{ matrix.fragments.version_new }}.
            - [Versions](https://registry.platformio.org/${{ matrix.fragments.type }}/${{ matrix.fragments.owner }}/${{ matrix.fragments.name }}/versions?version=${{ matrix.fragments.version_new }})
          branch: dependabot/platformio/${{ matrix.fragments.owner }}/${{ matrix.fragments.name }}-${{ matrix.fragments.version_new }}
          commit-message: Bump ${{ matrix.fragments.owner }}/${{ matrix.fragments.name }} from ${{ matrix.fragments.version_old }} to ${{ matrix.fragments.version_new }} in /
          labels: |
            dependencies
            firmware
          milestone: ${{ needs.context.outputs.milestone }}
          title: Bump ${{ matrix.fragments.owner }}/${{ matrix.fragments.name }} from ${{ matrix.fragments.version_old }} to ${{ matrix.fragments.version_new }}

      - name: GitHub Script close superseded
        if: ${{ fromJSON(steps.check.outputs.create) }}
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        with:
          script: |
            for (const pr of await github.paginate(
              github.rest.pulls.list,
              {
                owner: context.repo.owner,
                repo: context.repo.repo,
                state: 'open',
                base: '${{ github.ref_name }}',
                per_page: 100,
              }
            )) {
              if (
                pr.number !== Number(${{ steps.pr.outputs.pull-request-number }}) &&
                pr.user.type === 'Bot' &&
                pr.head.ref.startsWith('dependabot/platformio/${{ matrix.fragments.owner }}/${{ matrix.fragments.name }}-')
              ) {
                await github.rest.issues.createComment({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: pr.number,
                  body: 'Superseded by #${{ steps.pr.outputs.pull-request-number }}.',
                });
                await github.rest.issues.update({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: pr.number,
                  milestone: null,
                });
                await github.rest.pulls.update({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  pull_number: pr.number,
                  state: 'closed',
                });
                core.info(`Closed PR #${pr.number}`);
              }
            }
