name: Dependabot Updates PlatformIO

on:
  schedule:
    - cron: 9 5 * * 1-5

  workflow_dispatch:

jobs:
  platformio:
    name: Update PlatformIO dependencies
    runs-on: ubuntu-slim
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: PlatformIO Dependency Updater
        uses: VIPnytt/platformio-dependency-updater@16a5978cf218a60c5868f5287b8bb46bc1fec012 # v1.0.0-b1
