name: End of life

on:
  schedule:
    - cron: 24 7 31 * *

  workflow_dispatch:

permissions:
  contents: read

jobs:
  idle-check:
    name: Idle check
    runs-on: ubuntu-slim

    outputs:
      active: ${{ steps.idle.outputs.active }}

    steps:
      - name: GitHub Script idle check
        id: idle
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        with:
          script: |
            const { data: branch } = await github.rest.repos.getBranch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              branch: '${{ github.ref_name }}',
            });
            const active = new Date() - new Date(branch.commit.commit.committer.date) <= 90 * 86400000;
            core.info(`Branch active: ${active}`);
            core.setOutput('active', active);

  node:
    name: Node.js
    needs: idle-check
    runs-on: ubuntu-slim
    if: ${{ fromJSON(needs.idle-check.outputs.active) }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - node-version: 24

    steps:
      - name: End-of-Life
        uses: sindrel/endoflife-github-action@5f91adaabc542a346876290ff0f447c7bc355f99 # v1.0.3
        with:
          product: nodejs
          version: ${{ matrix.node-version }}
          fail_on_eol: true

  python:
    name: Python
    needs: idle-check
    runs-on: ubuntu-slim
    if: ${{ fromJSON(needs.idle-check.outputs.active) }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - python-version: '3.10'
          - python-version: 3.13
          - python-version: 3.14

    steps:
      - name: End-of-Life
        uses: sindrel/endoflife-github-action@5f91adaabc542a346876290ff0f447c7bc355f99 # v1.0.3
        with:
          product: python
          version: ${{ matrix.python-version }}
          fail_on_eol: true
