name: Generate

on:
  pull_request:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: read

jobs:
  font-dejavusans:
    name: DejaVuSans font
    runs-on: ubuntu-latest

    strategy:
      matrix:
        toolchain:
          - python-version: '3.10'
          - python-version: 3.14

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up uv
        uses: astral-sh/setup-uv@cec208311dfd045dd5311c1add060b2062131d57 # v8.0.0
        with:
          version-file: pyproject.toml
          python-version: ${{ matrix.toolchain.python-version }}
          activate-environment: true

      - name: Set up Python dependencies
        run: uv sync --extra font --no-dev

      - name: Font generator
        run: |
          python extra/Python/FontGenerator.py -i DejaVuSans --size 8

          mv DejaVuSansFont.cpp firmware/src/fonts
          mv DejaVuSansFont.h firmware/include/fonts

      - name: Clang
        if: ${{ matrix.toolchain.python-version != 3.14 }}
        uses: cpp-linter/cpp-linter-action@24467985494bed9bfc398489b6ec12469beaf4da # v2.17.0
        id: clang
        env:
          clang-version: 22
        with:
          version: ${{ env.clang-version }}
          files-changed-only: false
          ignore: "*|!firmware/src/fonts/DejaVuSansFont.cpp|!firmware/include/fonts/DejaVuSansFont.h"
          step-summary: true
          style: file
          tidy-checks: "-*"

      - name: Clang summary
        if: ${{ matrix.toolchain.python-version != 3.14 }}
        env:
          clang-threshold: 0
        run: |
          echo "Status: ${{ steps.clang.outputs.checks-failed }} checks failed, threshold for success is ${{ env.clang-threshold }}."
          echo "Clang report:"
          if [ -n "${{ github.event.pull_request.number }}" ]; then
            echo "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}?pr=${{ github.event.pull_request.number }}"
          else
            echo "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          fi
          exit $(( ${{ steps.clang.outputs.checks-failed }} > ${{ env.clang-threshold }} ))

  mode-dynamic:
    name: Dynamic mode
    runs-on: ubuntu-latest

    strategy:
      matrix:
        toolchain:
          - python-version: '3.10'
          - python-version: 3.14

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up Cache for PlatformIO
        continue-on-error: true
        uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5.0.4
        with:
          key: platformio-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('platformio.ini') }}
          path: .platformio/.cache

      - name: Set up uv
        uses: astral-sh/setup-uv@cec208311dfd045dd5311c1add060b2062131d57 # v8.0.0
        with:
          version-file: pyproject.toml
          python-version: ${{ matrix.toolchain.python-version }}
          activate-environment: true

      - name: Set up PlatformIO
        run: uv sync --only-group platformio

      - name: Generate mode
        run: |
          cat <<EOL > Dynamic.csv
          0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
          0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
          0,0,0,255,0,0,0,0,0,255,0,0,255,0,0,0
          0,0,0,255,0,0,0,0,0,0,0,0,255,0,0,0
          0,0,0,255,255,255,0,0,0,255,0,0,255,0,0,0
          0,0,0,255,0,0,255,0,0,255,0,0,255,0,0,0
          0,0,0,255,0,0,255,0,0,255,0,0,0,0,0,0
          0,0,0,255,0,0,255,0,0,255,0,0,255,0,0,0
          0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
          0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
          0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
          0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
          0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
          0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
          0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
          0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
          0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
          0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
          0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
          0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
          0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
          0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
          0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
          0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
          0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
          0,0,0,0,255,255,0,0,0,0,255,255,0,0,0,0
          0,0,0,0,255,255,0,0,0,0,255,255,0,0,0,0
          0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
          0,0,0,0,255,255,0,0,0,0,255,255,0,0,0,0
          0,0,0,0,0,255,255,255,255,255,255,0,0,0,0,0
          0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
          0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
          EOL

          python extra/Python/ModeGenerator.py -i Dynamic.csv

          mv DynamicMode.cpp firmware/src/modes
          mv DynamicMode.h firmware/include/modes

          sed -i '/^#pragma once$/a\#include "modes/DynamicMode.h"' firmware/include/services/ModesService.h
          sed -i '/^    inline static const std::vector<ModeModule \*> modes{$/a\        new DynamicMode(),' firmware/include/services/ModesService.h

      - name: PlatformIO build
        run: |
          cat <<'EOL' > .env
          HOSTNAME='frekvens'
          IKEA_FREKVENS='true'
          MODE_ANIMATION='true'
          NAME='Frekvens'
          EOL

          cat <<'EOL' > firmware/include/config/secrets.h
          #pragma once
          #define PIN_CS 1
          #define PIN_MOSI 2
          #define PIN_OE 3
          #define PIN_SCLK 4
          #define WIFI_KEY "redacted"
          #define WIFI_SSID "redacted"
          EOL

          pio run -e esp32dev

      - name: PlatformIO compilation database
        if: ${{ matrix.toolchain.python-version != 3.14 }}
        run: pio run -e esp32dev -t compiledb

      - name: Clang
        if: ${{ matrix.toolchain.python-version != 3.14 }}
        uses: cpp-linter/cpp-linter-action@24467985494bed9bfc398489b6ec12469beaf4da # v2.17.0
        id: clang
        env:
          clang-version: 22
        with:
          version: ${{ env.clang-version }}
          files-changed-only: false
          ignore: "*|!firmware/src/modes/DynamicMode.cpp|!firmware/include/modes/DynamicMode.h"
          step-summary: true
          style: file
          tidy-checks: ""

      - name: Clang summary
        if: ${{ matrix.toolchain.python-version != 3.14 }}
        env:
          clang-threshold: 0
        run: |
          echo "Status: ${{ steps.clang.outputs.checks-failed }} checks failed, threshold for success is ${{ env.clang-threshold }}."
          echo "Clang report:"
          if [ -n "${{ github.event.pull_request.number }}" ]; then
            echo "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}?pr=${{ github.event.pull_request.number }}"
          else
            echo "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          fi
          exit $(( ${{ steps.clang.outputs.checks-failed }} > ${{ env.clang-threshold }} ))

  mode-static:
    name: Static mode
    runs-on: ubuntu-latest

    strategy:
      matrix:
        toolchain:
          - python-version: '3.10'
          - python-version: 3.14

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up Cache for PlatformIO
        continue-on-error: true
        uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5.0.4
        with:
          key: platformio-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('platformio.ini') }}
          path: .platformio/.cache

      - name: Set up uv
        uses: astral-sh/setup-uv@cec208311dfd045dd5311c1add060b2062131d57 # v8.0.0
        with:
          version-file: pyproject.toml
          python-version: ${{ matrix.toolchain.python-version }}
          activate-environment: true

      - name: Set up PlatformIO
        run: uv sync --only-group platformio

      - name: Generate mode
        run: |
          cat <<EOL > Static.csv
          0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
          0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
          0,0,0,255,0,0,0,0,0,255,0,0,255,0,0,0
          0,0,0,255,0,0,0,0,0,0,0,0,255,0,0,0
          0,0,0,255,255,255,0,0,0,255,0,0,255,0,0,0
          0,0,0,255,0,0,255,0,0,255,0,0,255,0,0,0
          0,0,0,255,0,0,255,0,0,255,0,0,0,0,0,0
          0,0,0,255,0,0,255,0,0,255,0,0,255,0,0,0
          0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
          0,0,0,0,255,255,0,0,0,0,255,255,0,0,0,0
          0,0,0,0,255,255,0,0,0,0,255,255,0,0,0,0
          0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
          0,0,0,0,255,255,0,0,0,0,255,255,0,0,0,0
          0,0,0,0,0,255,255,255,255,255,255,0,0,0,0,0
          0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
          0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
          EOL

          python extra/Python/ModeGenerator.py -i Static.csv

          mv StaticMode.cpp firmware/src/modes
          mv StaticMode.h firmware/include/modes

          sed -i '/^#pragma once$/a\#include "modes/StaticMode.h"' firmware/include/services/ModesService.h
          sed -i '/^    inline static const std::vector<ModeModule \*> modes{$/a\        new StaticMode(),' firmware/include/services/ModesService.h

      - name: PlatformIO build
        run: |
          cat <<'EOL' > .env
          HOSTNAME='frekvens'
          IKEA_FREKVENS='true'
          MODE_DRAW='true'
          NAME='Frekvens'
          EOL

          cat <<'EOL' > firmware/include/config/secrets.h
          #pragma once
          #define PIN_CS 1
          #define PIN_MOSI 2
          #define PIN_OE 3
          #define PIN_SCLK 4
          #define WIFI_KEY "redacted"
          #define WIFI_SSID "redacted"
          EOL

          pio run -e esp32dev

      - name: PlatformIO compilation database
        if: ${{ matrix.toolchain.python-version != 3.14 }}
        run: pio run -e esp32dev -t compiledb

      - name: Clang
        if: ${{ matrix.toolchain.python-version != 3.14 }}
        uses: cpp-linter/cpp-linter-action@24467985494bed9bfc398489b6ec12469beaf4da # v2.17.0
        id: clang
        env:
          clang-version: 22
        with:
          version: ${{ env.clang-version }}
          files-changed-only: false
          ignore: "*|!firmware/src/modes/StaticMode.cpp|!firmware/include/modes/StaticMode.h"
          step-summary: true
          style: file
          tidy-checks: ""

      - name: Clang summary
        if: ${{ matrix.toolchain.python-version != 3.14 }}
        env:
          clang-threshold: 0
        run: |
          echo "Status: ${{ steps.clang.outputs.checks-failed }} checks failed, threshold for success is ${{ env.clang-threshold }}."
          echo "Clang report:"
          if [ -n "${{ github.event.pull_request.number }}" ]; then
            echo "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}?pr=${{ github.event.pull_request.number }}"
          else
            echo "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          fi
          exit $(( ${{ steps.clang.outputs.checks-failed }} > ${{ env.clang-threshold }} ))
