name: IKEA Frekvens LED spotlight

on:
  pull_request:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: read

jobs:
  esphome:
    name: ESPHome minimum version
    runs-on: ubuntu-latest
    outputs:
      min_version: ${{ steps.config.outputs.min_version }}

    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: ESPHome minimum version
        id: config
        run: echo "min_version=$(grep "  min_version:" "extra/IKEA-Frekvens-LED-spotlight/esphome.yaml" | cut -d '"' -f 2)" >> "$GITHUB_OUTPUT"

  ikea-frekvens-led-spotlight:
    name: ESPHome
    needs: esphome
    runs-on: ubuntu-latest
    continue-on-error: true

    strategy:
      matrix:
        esphome-version:
          - ${{ needs.esphome.outputs.min_version }}
          - latest

    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Set up ESPHome secrets.yaml
        run: |
          cat <<EOL > extra/IKEA-Frekvens-LED-spotlight/secrets.yaml
          api_key: "redacted"
          ota_password: "redacted"
          wifi_password: "redacted"
          wifi_ssid: "redacted"
          EOL

      - name: ESPHome build
        uses: esphome/build-action@4ef4722a2935eac47b7e227fe0e1f8e0f8afcc42 # v7.3.0
        with:
          version: ${{ matrix.esphome-version }}
          yaml-file: extra/IKEA-Frekvens-LED-spotlight/esphome.yaml
